package:
    name: hubward
    version: "0.1"

source:
    #git_url: https://github.com/daler/hubward
    #git_rev: master
    path: ../..

build:
    number: 1

requirements:
    build:
        - python
        - jsonschema
        - setuptools
        - bleach
        - pybedtools
        - fabric
        - colorama
        - trackhub
        - matplotlib
        - pyaml
        - docutils
        - sh

    run:
        - python
        - bleach
        - pybedtools
        - jsonschema
        - fabric
        - colorama
        - trackhub
        - pyaml
        - matplotlib
        - docutils
        - sh

test:
    imports:
        - hubward

